<div class="o-stage__inner">
	<figure class="o-stage__logo">
		<img src="<?= $data->logo; ?>" alt="<?= $data->logoAlt; ?>">
	</figure>

	<div class="o-stage__intro__outer">
		<p class="o-stage__intro">
			<?= $data->text; ?>
		</p>
	</div>

	<ul class="o-stage__links">

		<?php while (have_rows('stage_button_links')): the_row(); ?>

			<?php
			$icon = get_sub_field('cta_icon');
			?>

			<li class="o-stage__item">
				<a href="#<?= get_sub_field('cta_target') ?>" class="o-stage__link js-link">
					<i class="o-stage__item__icon icomoon-<?= get_sub_field('cta_icon') ?>"></i>
					<?= get_sub_field('cta_link_name') ?>
				</a>
			</li>

		<? endwhile; ?>

	</ul>
</div>

