<div class="o-search__inner">
	<form role="search" method="get" class="o-search__form" action="<?php echo esc_url(home_url('/')); ?>">
		<label for="search" class="o-search__label h-vh"><? _ex('Search', 'label', 'nxtheme'); ?></label>
		<input id="search" type="search" class="o-search__input"
		       placeholder="<?= esc_attr_x('Search', 'placeholder', 'nxtheme'); ?>"
		       value="<?php echo esc_attr(get_search_query()); ?>" name="s">
		<button type="submit" class="o-search__button"><?= esc_attr_x('Search', 'submit button', 'nxtheme'); ?></button>
	</form>
</div>
