<? if ($data->query->have_posts()) : ?>

	<ul class="o-teaserlist__list">
		<? while ($data->query->have_posts()): $data->query->the_post(); ?>

			<?php if (have_rows('flexible_content_sub')): ?>

			<li class="o-teaserlist__item">
				<?= module('teaser')
					->ctrl(); ?>
			</li>

			<?php endif; ?>

		<? endwhile; ?>
	</ul>
<? else : ?>

	<!-- Content Module -->
	<div class="o-content">
		<div class="o-content__inner">
			<div class="o-content__one">
				No results found.
			</div>
		</div>
	</div>

<?php endif; ?>
