<div class="inner page-centered box-content">
	<div class="g-row g-layout-footer">
		<div class="g-col g-col-1 tags">
				<? if ($data->menu_one !== false): ?>
				<h2 class="footer-item-title"><?= $data->menu_one['label']; ?></h2>
				<? wp_tag_cloud() ?>
			<? endif; ?>
		</div>
		<div class="g-col g-col-1">
			<? if ($data->menu_two !== false): ?>
			<h2 class="footer-item-title"><?= $data->menu_two['label']; ?></h2>
			<ul class="linklist">
				<? foreach ($data->menu_two['items'] as $item) : ?>
				<li class="list-item"><a href="<?= $item->url ?>" target="<?= $item->target ?>"><?= $item->title ?></a></li>
			<? endforeach; ?>
		</ul>
	<? endif; ?>
	</div>
	<div class="g-col g-col-1">
		<? if ($data->menu_social !== false): ?>
		<h2 class="footer-item-title"><?= $data->menu_social['label']; ?></h2>
		<ul class="linklist social">
			<? foreach ($data->menu_social['items'] as $item) : ?>
			<li class="list-item"><a href="<?= $item->url ?>" class="icon <?= implode(' ', $item->classes) ?>" target="<?= $item->target ?>"><span class="h-vh"><?= $item->title ?></span></a></li>
		<? endforeach; ?>
	</ul>
	<? endif; ?>
	</div>
</div>
</div>
<div class="ft">
	<div class="page-centered box-content">
		Netzwaerk © <?= date('Y') ?>
	</div>
</div>