<div class="o-footer__inner">
	<h4 class="o-footer__title">
		<?= $data->title ?>
	</h4>

	<address class="o-footer__address">
		<?= $data->address ?>
	</address>

	<div class="o-footer__contact-wrapper">
		<div class="o-footer__contact-wrapper__inner">
			<a href="tel:<?= $data->mobilelink ?>" class="o-footer__tel">
				<i class="icon-ios-telephone-outline"></i>
				<?= $data->mobile ?>
			</a>

			<a href="mailto:<?= $data->email ?>" class="o-footer__mail">
				<i class="icon-ios-email-outline"></i>
				<?= $data->email ?>
			</a>
		</div>
	</div>

</div>

<a class="o-footer__disclaimer" href="/disclaimer">Disclaimer</a>
