<div class="o-accordion__inner js-accordion">

	<?php if($data->title) : ?>
		<h3 class="o-accordion__title"><?= $data->title ?></h3>
	<?php endif; ?>

	<?php if(get_sub_field('accordion_show_filter')) : ?>
		<input type="text" placeholder="Filter" class="a-input o-accordion__filter js-accordion-filter a-input">
	<?php endif; ?>

	<?php if (have_rows('accordion_item')): ?>

		<ul class="o-accordion__list js-accordion-list">

		<?php while (have_rows('accordion_item')) : the_row() ?>

			<li class="o-accordion__item js-accordion-item">
				<h3 class="o-accordion__item__title js-accordion-title">
					<?= get_sub_field('accordion_item_title') ?>
					<span class="o-accordion__item__chevron"></span>
				</h3>
				<div class="o-accordion__item__body js-accordion-body">
					<?= get_sub_field('accordion_item_content') ?>
				</div>
			</li>

		<?php endwhile; ?>
		</ul>

	<?php endif; ?>

</div>

