<div class="o-platform__inner" style="background-image: url(<?= $data->background_image['url']; ?>)">

	<h1 class="o-platform__title"><?= $data->title; ?></h1>

	<p class="o-platform__text"><?= $data->text; ?></p>

	<?php if(have_rows('platform_logos')) : ?>

		<ul class="o-platform__logos">

		<?php while (have_rows('platform_logos')) : the_row() ?>

			<li class="o-platform__logo">

				<?php
				$image = get_sub_field('platform_logo');
				$imageUrl = $image['url'];
				?>

				<img src="<?= $imageUrl ?>" alt="">

			</li>

		<?php endwhile; ?>

		</ul>

	<?php endif; ?>

</div>
