<div id="<?= $data->anchor ?>" class="o-content__inner js-content">
	<h2 class="o-content__title">
		<i class="icomoon-<?= $data->anchor ?>"></i>
		<?= $data->title ?>
	</h2>

	<div class="o-content__copy">
		<div class="o-content__copy__left<? if(!$data->copyRight) { echo 'o-content__copy__left--only'; } ?> ">
			<?= $data->copyLeft ?>
		</div>

		<div class="o-content__copy__right">
			<?= $data->copyRight ?>
		</div>
	</div>

	<div class="o-content__cta">
		<p class="o-content__cta__info">
			<?= $data->buttonInfo ?>
		</p>

		<?php if($data->buttonTarget) : ?>
			<a href="#<?= $data->buttonTarget ?>" data-form="<?= $data->formText ?>" class="o-content__cta__btn a-btn js-link js-link-contact">
				<?= $data->buttonTitle ?>
			</a>
		<?php endif; ?>

	</div>
</div>