<div class="o-imagelist__inner">

	<h3 class="o-imagelist__title">
		<?= $data->title ?>
	</h3>

	<?php if (have_rows('image_list')) : ?>

		<ul class="o-imagelist__list">
			<?php while (have_rows('image_list')) : the_row() ?>

				<?php $image = get_sub_field('image') ?>

				<li class="o-imagelist__item">
					<img src="<?= $image['url'] ?>" alt="" class="o-imagelist__item__image">
				</li>

			<?php endwhile; ?>

		</ul>

	<? endif; ?>

</div>

